// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRHz2LrEl3OzdVugv5blXaH5FUjUyRXoo',
    appId: '1:774404697200:web:0cf1e4a2530578104858b5',
    messagingSenderId: '774404697200',
    projectId: 'pay-defteri',
    authDomain: 'pay-defteri.firebaseapp.com',
    storageBucket: 'pay-defteri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfA0qzGkHzKjtrcEYjnqa0HOsoAzUw3VU',
    appId: '1:774404697200:android:22d0dde0cbb75ce24858b5',
    messagingSenderId: '774404697200',
    projectId: 'pay-defteri',
    storageBucket: 'pay-defteri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDictM-ZLwJsJYXrusWSkNxFARWmwf6LGY',
    appId: '1:774404697200:ios:0a469d1a8064676c4858b5',
    messagingSenderId: '774404697200',
    projectId: 'pay-defteri',
    storageBucket: 'pay-defteri.firebasestorage.app',
    iosBundleId: 'com.example.pay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDictM-ZLwJsJYXrusWSkNxFARWmwf6LGY',
    appId: '1:774404697200:ios:0a469d1a8064676c4858b5',
    messagingSenderId: '774404697200',
    projectId: 'pay-defteri',
    storageBucket: 'pay-defteri.firebasestorage.app',
    iosBundleId: 'com.example.pay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRHz2LrEl3OzdVugv5blXaH5FUjUyRXoo',
    appId: '1:774404697200:web:b1cbbd0688643a404858b5',
    messagingSenderId: '774404697200',
    projectId: 'pay-defteri',
    authDomain: 'pay-defteri.firebaseapp.com',
    storageBucket: 'pay-defteri.firebasestorage.app',
  );
}
